#!/usr/bin/env python3
# -*- coding: utf-8 -*-

################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Author: Leon Jung, Gilbert

import rospy
import numpy as np
from enum import Enum
from std_msgs.msg import UInt8, Float64
from turtlebot3_autorace_msgs.msg import MovingParam


class CoreModeDecider():
    def __init__(self):
        # subscribes : invoking object detected
        self.sub_traffic_sign = rospy.Subscriber('/detect/traffic_sign', UInt8, self.cbInvokedByTrafficSign, queue_size=1)
        self.sub_traffic_light = rospy.Subscriber('/detect/traffic_light', UInt8, self.cbInvokedByTrafficLight, queue_size=1)

        self.sub_returned_mode = rospy.Subscriber('/core/returned_mode', UInt8, self.cbReturnedMode, queue_size=1)

        # publishes : decided mode
        self.pub_decided_mode = rospy.Publisher('/core/decided_mode', UInt8, queue_size=1)
        
        # publishes : speed limit
        self.pub_speed_limit = rospy.Publisher('/control/max_vel', Float64, queue_size=1)

        self.InvokedObject = Enum('InvokedObject', 'traffic_sign traffic_light')
        self.TrafficSign = Enum('TrafficSign', 'intersection left right construction stop parking tunnel speedlimit_50 speedlimit_100 traffic_light')
        self.CurrentMode = Enum('CurrentMode', 'idle lane_following traffic_light intersection construction parking level_crossing tunnel')

        # speed parameters for speed limit signs
        self.base_speed = 0.12
        self.current_speed = self.base_speed

        # helper variable to prevent repeated speed of same sign
        self.last_speed_sign = None

        self.last_sign_time = rospy.Time(0)
        self.sign_cooldown = rospy.Duration(3)  # Cooldown period of 3 seconds
        
        self.fnInitMode()

    # Invoke if traffic sign is detected
    def cbInvokedByTrafficSign(self, traffic_sign_type_msg):

        '''sign = traffic_sign_type_msg.data
        
        #Ignore repeated detection of same sign 
        if self.last_detected_sign == sign:
            rospy.loginfo("CoreModeDecide - Last Detect Sign") 
            return     
        self.last_detected_sign = sign

        if sign != self.TrafficSign.speedlimit_50.value and sign != self.TrafficSign.speedlimit_100.value:
            current_time = rospy.Time.now()
            if current_time - self.last_sign_time < self.sign_cooldown:
                rospy.loginfo("CoreModeDecide - Sign detection on cooldown") 
                return
            self.last_sign_time = current_time'''

        rospy.loginfo("cbInvokedByTrafficSign - Invoking sign")  
        self.fnDecideMode(self.InvokedObject.traffic_sign.value, traffic_sign_type_msg)
        rospy.loginfo("Traffic sign detected")
    
    # Invoke if traffic light is detected
    def cbInvokedByTrafficLight(self, traffic_light_type_msg):
        rospy.loginfo("cbInvokedByTrafficLight - Invoking light")  
        self.fnDecideMode(self.InvokedObject.traffic_light.value, traffic_light_type_msg)
        rospy.loginfo("Traffic light detected")

    def cbReturnedMode(self, mode):
        rospy.loginfo("cbReturnedMode - Return Mode")
        #self.last_detected_sign = None
        self.fnInitMode()

    def fnInitMode(self): 
        rospy.loginfo("fnInitMode - Init Mode")
        self.current_mode = self.CurrentMode.lane_following.value
        self.fnPublishMode()

    def fnDecideMode(self, invoked_object, msg_data):                               # starts only when the traffic sign / traffic light is detected & current_mode is lane_following
        rospy.loginfo("fnDecideMode - Decide Mode")
        if self.current_mode == self.CurrentMode.lane_following.value:
            rospy.loginfo("currentmode : lane following")

            if invoked_object == self.InvokedObject.traffic_light.value:            # Traffic Light detected
                rospy.loginfo("Traffic Light detected")
                self.current_mode = self.CurrentMode.traffic_light.value
            
            if invoked_object == self.InvokedObject.traffic_sign.value:             # Any Sign detected
                rospy.loginfo("Any Sign detected")

                msg_speed_limit = Float64()
                
                if msg_data.data == self.TrafficSign.intersection.value:            # Intersection Sign detected
                    self.current_mode = self.CurrentMode.intersection.value
                    rospy.loginfo("Detect Sign : intersection")
                
                elif msg_data.data == self.TrafficSign.construction.value:          # Construction Sign detected
                    self.current_mode = self.CurrentMode.construction.value
                    rospy.loginfo("Detect Sign : construction")
                
                elif msg_data.data == self.TrafficSign.stop.value:                  # Stop Sign detected
                    self.current_mode = self.CurrentMode.level_crossing.value
                    rospy.loginfo("Detect Sign : stop")
                    
                elif msg_data.data == self.TrafficSign.parking.value:               # Parking Sign detected
                    self.current_mode = self.CurrentMode.parking.value
                    rospy.loginfo("Detect Sign : Parking")
                    
                elif msg_data.data == self.TrafficSign.tunnel.value:                # Tunnel Sign detected
                    self.current_mode = self.CurrentMode.tunnel.value
                    rospy.loginfo("Detect Sign : Tunnel")

                elif msg_data.data == self.TrafficSign.speedlimit_50.value:         # Speed Limit 50 Sign detected
                    
                    if self.last_speed_sign != 50:
                        msg_speed_limit.data = self.base_speed * 0.5
                        self.pub_speed_limit.publish(msg_speed_limit)
                        rospy.loginfo("Detect Sign : Speed Limit 50")
                        self.last_speed_sign = 50

                elif msg_data.data == self.TrafficSign.speedlimit_100.value:        # Speed Limit 100 Sign detected
                    
                    if self.last_speed_sign != 100:
                        msg_speed_limit.data = self.base_speed * 1.0
                        self.pub_speed_limit.publish(msg_speed_limit)
                        rospy.loginfo("Detect Sign : Speed Limit 100")
                        self.last_speed_sign = 100

                elif msg_data.data == self.TrafficSign.traffic_light.value:         # Traffic Light Sign detected
                    self.current_mode = self.CurrentMode.traffic_light.value
                    msg_speed_limit.data = 0.08
                    self.pub_speed_limit.publish(msg_speed_limit)
                    rospy.loginfo("Detect Sign : Traffic Light")
            else:
                pass

            self.fnPublishMode()

        else:
            pass

    def fnPublishMode(self):
        decided_mode = UInt8()
        decided_mode.data = self.current_mode
        self.pub_decided_mode.publish(decided_mode)

    def main(self):
        rospy.spin()

if __name__ == '__main__':
    rospy.init_node('core_mode_decider')
    node = CoreModeDecider()
    node.main()
